### ISSUE TITLE
--custom-output does not work

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-load-test#4]
It says

```
File "/usr/local/lib/python3.7/site-packages/invokust/loadtest.py", line 33, in stats
    'num_requests': runners.locust_runner.stats.num_requests,
AttributeError: module 'locust.runners' has no attribute 'locust_runner'
```

Likely just a change from locust_runner to locust.runner? Or maybe an old or new python version?

A similar problem seems to exist for the debug option:

```
[2020-04-09 19:20:04,957] d7075656143b/ERROR/locust.core: unsupported operand type(s) for +=: 'EventHook' and 'function'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/locust/core.py", line 235, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.7/site-packages/locust/core.py", line 261, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/usr/local/lib/python3.7/site-packages/locust/core.py", line 364, in execute_task
    task(self.locust).run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/locust/core.py", line 221, in run
    self.on_start()
  File "/app/personas/vrp.py", line 19, in on_start
    common.setup_locust_debugging()
  File "/app/personas/common.py", line 59, in setup_locust_debugging
    events.request_failure += report_error
TypeError: unsupported operand type(s) for +=: 'EventHook' and 'function'
```

The reason seems to be the snapshot locust version introduced in #3.
